### ISSUE TITLE
fetchMessages before/after arguments error

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [qeled/discordie#34]
![image](https://cloud.githubusercontent.com/assets/10401817/17613233/2ecba524-6085-11e6-80db-649d1503e555.png)

As [said in docs](https://qeled.github.io/discordie/#/docs/ITextChannel?p=ITextChannel%23fetchMessages&_k=m2a8c3), arguments `after` and `before` can be set to `null`. But now if they set to null, library still makes request with `after`/`before` parameters set to `""` (empty string), Discord no longer allows this and prints error:

```js
{"after": ["Value \"\" is not long."]}
```

**Comment by abalabahaha** [comment]
This was fixed in this Github repo with commit 31aeaed based on PR #33. It looks like it hasn't made it to a NPM release, but that shouldn't be far off

**Comment by DaFri-Nochiterov** [comment]
But, if they set to `null` - error still here. Need some checks :wink:

I think `channel.fetchMessages(100, null, "1231337456666111")` will be rejected with same error

**Comment by abalabahaha** [comment]
It works if you leave it as undefined. The issue was that Superagent sends null keys as `?before=` (which Discord now hates starting from an update yesterday), whereas undefined keys are not sent at all.

**Comment by DaFri-Nochiterov** [comment]
Then why not check arguments and replace `null` to `undefined`?

**Comment by abalabahaha** [comment]
qeled just committed f628e1a :P My PR originally had it, for some reason that was removed, but it's back now.

**Comment by DaFri-Nochiterov** [comment]
Fixed in f628e1a12861006b842594d0ddd93fc1f45fb722 :+1:
